---
version: "2.0"
services:
  mem-carbon:
    image: decentland/mem-carbon-testnet:0.0.2
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
profiles:
  compute:
    mem-carbon:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        mem-carbon:
          denom: uakt
          amount: 1000
deployment:
  mem-carbon:
    dcloud:
      profile: mem-carbon
      count: 1
